### ISSUE TITLE
Onewire Bricklet

### ISSUE THREAD

**Issue by jheising** [Tinkerforge/one-wire-bricklet#1]
Hi all, if it helps I've created a working onewire bricklet already at: https://github.com/jheising/onewire-bricklet. Please feel free to use in any way you want.

**Comment by borg42** [comment]
Yes, we already saw it. Looks very good! The 1-Wire Bricklet will get a co-processor instead of the EEPROM (as all new Brickelts get now), so we will be able to use the UART hardware unit and implement it like this: https://www.maximintegrated.com/en/app-notes/index.mvp/id/214

We can use the UART FIFO and interrupts etc. Thus we can't unfortunately use a lot of the code that you wrote.

**Comment by borg42** [comment]
The first low level stuff is now implemented and tested. We will probably add some more functions for standard 1-wire sensors like the DS18B20.
